### ISSUE TITLE
categorize tokens

### ISSUE THREAD

**Issue by jettjaniak** [jettjaniak/tinyevals#9]
- [our tokenizer](https://huggingface.co/jbrinkma/delphi-100k) has < 4,000 meaningful tokens
- let's look through all of them and assign to various groups, like
  - names
  - starting with space
  - captialized
  - noun
  - plural
  - singular
  - part of a word
  - subject
  - etc.
- we will need that to analyze per-token loss across models and training epochs

**Comment by joshuawe** [comment]
## What kind of token categorization exists? (Google & GPT4)

> Part-of-Speech Tagging (POS Tagging): This involves labeling each word with its part of speech (noun, verb, adjective, etc.). This can be done using libraries like NLTK or spaCy in Python. POS tagging helps in understanding the grammatical structure of sentences.
> 
> Semantic Categorization: Grouping words based on their meanings or semantic similarities. This can be achieved through techniques like word embeddings (e.g., Word2Vec, GloVe) which represent words in a continuous vector space. Words with similar meanings are closer in this space. Clustering algorithms can then be applied to these embeddings to group similar words.
> 
> Named Entity Recognition (NER): This is the process of identifying and categorizing key information (entities) in text into predefined categories such as the names of persons, organizations, locations, expressions of times, quantities, monetary values, etc.
> 
> Frequency Analysis: Categorizing words based on their frequency of occurrence. High-frequency words might often be common words or stop words, whereas low-frequency ones might be more topic-specific or rare.
> 
> Syntactic Categorization: Categorizing words based on their syntactic roles or patterns in sentences. This could involve identifying subjects, objects, predicates, etc.
> 
> Lexical Resource-Based Categorization: Utilizing lexical resources like WordNet to categorize words into synsets (sets of synonyms that share a common meaning).

## So, what should we use, NLTK or spaCy?  
https://www.nltk.org/  and   https://spacy.io/usage/rule-based-matching

> Key Differences Between NLTK and spaCy
> 
> - Performance: spaCy is generally faster and more efficient for larger texts, as it uses the latest algorithms.
> - Accuracy: spaCy's models are usually more accurate as they are trained on larger and more diverse datasets.
> - Ease of Use: spaCy's API is often considered more user-friendly and intuitive.
> 
> You can choose either based on your specific needs, such as the size and complexity of your dataset, the level of accuracy required, and your familiarity with the library. For a quick, straightforward task, NLTK is a great choice. For more complex needs, or if you're planning to scale your project, spaCy might be more suitable.

So I would say, let's go with spaCy.

## We use our own custom tokenizer and for now go through token by token.
**Note: Token by token loses some of the token's meaning as they can vary depending on their relative position with other tokens -> context. So tokens are not iid, but for now treated as such.** (Maybe check later how many of our tokens have this issue and see if spaCy can indicate the 'token ambiguity').

Installation (English language capabilities)
```Python
pip install spacy
python -m spacy download en_core_web_sm
import spacy
nlp = spacy.load("en_core_web_sm")
```

## Basic category implementation

```Python
for token in your_token_list:
    # Process each token
    doc = nlp(token)
    for word in doc:
        print(f"Token: {word.text}")
        print(f"Starts with Space: {'Yes' if word.text.startswith(' ') else 'No'}")
        print(f"Capitalized: {'Yes' if word.text[0].isupper() else 'No'}")
        print(f"POS Tag: {word.pos_}")
        print(f"Is Noun: {'Yes' if word.pos_ == 'NOUN' else 'No'}")
        # Add other categories as needed
```


**Note: It is recommended to analyze sentences and not words, due to context, as mentioned before.**

**Comment by joshuawe** [comment]
To install spaCy we need to run two commands. Install spacy this way:
`pip install spacy`

To download spaCy's English language capabilities we need to run
`python -m spacy download en_core_web_sm`

Edit:
Found a way to avoid this and include it into the main body of the script when it is imported, it will run 
`spacy.cli.download("en_core_web_sm", False, False, '-q')`
It will download it and should be able to use the downloaded language packet (a language model) immediately. If worst comes to worst, the script needs to be rerun (the Python process needs to be restarted).

**Comment by jettjaniak** [comment]
Will it redownload it each time, or use a cached version?

**Comment by joshuawe** [comment]
> Will it redownload it each time, or use a cached version?

@jettjaniak It will use the cached version if it has been downloaded before.

But there is another thing we should take into account.

So, spaCy is an entire library with many NLP functionalities. You can also use it during training to include small token pertubations etc.
One thing it recommends the user to do is instead of passing the token by token output to be analysed, it likes to look at the whole token sequence as a single string. Because if a word is composed of two tokens such as `high` and `way` for highway. Or another example could be that the word *cars* is composed of two tokens as `car` `s` . 
-> Hence, providing a label for each of the tokens individually could result in wrong labelling.

**BUT** this would lead away from assessing individual token performance. 
Now the question is do we want to remain at single token performance or are we also interested at performance such as part of speech  with _adjectives, nouns, verbs, ...,_ and grammatical relationship between words such as _subject, preposition, compound_?
Then it would be wise to either only look at these categories and try to match the loss of the individual tokens to the given token labels/categories.

A look up table (= fixed label) for a token is not a good idea. E.g. is `sentence` a noun or a verb? It can be used as both:
- Noun: The sentence is long.
- Verb: We sentence you to five months in prison.

Are we really sure/desperate to look at individual token loss over grouped loss?

**Comment by jettjaniak** [comment]
Each token should get all the labels that apply. This is much less
ambiguous in TinyStories than it is in general English.
Let's start with labeling single tokens, I'll try to elaborate on it
tomorrow.

**Comment by jettjaniak** [comment]
moved https://github.com/delphi-suite/delphi/issues/12 please accept the invite and assign yourself
